extends SceneTree
## Rebuild frame rectangles without modifying the user-supplied PNGs.
func _initialize() -> void:
	var result := {}
	for race in ["saiyan", "fist", "mazoku", "witch_warlock", "patryn"]:
		var source := Image.new()
		var error := source.load("res://assets/characters/%s.png" % race)
		if error != OK or source.is_empty() or source.get_size() != Vector2i(1086, 1448):
			push_error("Invalid or missing sprite sheet: %s; expected 1086x1448" % race)
			quit(1)
			return
		var frames := []
		for row in range(4):
			for column in range(3):
				var cell := Rect2i(column * 362, row * 362, 362, 362)
				var part := source.get_region(cell)
				var bounds := part.get_used_rect()
				if not bounds.has_area():
					push_error("Empty sprite cell: %s row %d column %d" % [race, row, column])
					quit(1)
					return
				# Anchor between the boots, ignoring hair, capes, tails and staves.
				var foot_left := 362
				var foot_right := 0
				for y in range(maxi(bounds.position.y, bounds.end.y - 24), bounds.end.y):
					for x in range(bounds.position.x, bounds.end.x):
						if part.get_pixel(x, y).a > 0.5:
							foot_left = mini(foot_left, x)
							foot_right = maxi(foot_right, x)
				# Faint edge pixels may extend below the boots; use cell center if needed.
				if foot_left > foot_right:
					foot_left = 181
					foot_right = 181
				frames.append({"rect": [cell.position.x + bounds.position.x, cell.position.y + bounds.position.y, bounds.size.x, bounds.size.y], "anchor": [(foot_left + foot_right) * 0.5 - bounds.position.x, bounds.size.y]})
		result[race] = frames
	var text := "extends RefCounted\n# Generated by tools/build_sprite_regions.gd.\nconst DATA := {\n"
	for race in result:
		text += "\t\"%s\": [\n" % race
		for frame in result[race]:
			text += "\t\t" + JSON.stringify(frame) + ",\n"
		text += "\t],\n"
	text += "}\n"
	var file := FileAccess.open("res://assets/characters/regions.gd", FileAccess.WRITE)
	if file == null:
		push_error("Cannot write sprite regions: %s" % error_string(FileAccess.get_open_error()))
		quit(1)
		return
	file.store_string(text)
	file.flush()
	if file.get_error() != OK:
		push_error("Failed writing sprite regions")
		quit(1)
		return
	quit()
