extends SceneTree
## Rebuild frame rectangles without modifying the user-supplied PNGs.
func _initialize() -> void:
	var result := {}
	for race in ["saiyan", "fist", "mazoku", "witch_warlock", "patryn"]:
		var source := Image.load_from_file("res://assets/characters/%s.png" % race)
		var frames := []
		for row in range(4):
			for column in range(3):
				var cell := Rect2i(column * 362, row * 362, 362, 362)
				var part := source.get_region(cell)
				var bounds := part.get_used_rect()
				# Anchor between the boots, ignoring hair, capes, tails and staves.
				var foot_left := 362
				var foot_right := 0
				for y in range(bounds.end.y - 24, bounds.end.y):
					for x in range(bounds.position.x, bounds.end.x):
						if part.get_pixel(x, y).a > 0.5:
							foot_left = mini(foot_left, x)
							foot_right = maxi(foot_right, x)
				frames.append({"rect": [cell.position.x + bounds.position.x, cell.position.y + bounds.position.y, bounds.size.x, bounds.size.y], "anchor": [(foot_left + foot_right) * 0.5 - bounds.position.x, bounds.size.y]})
		result[race] = frames
	var text := "extends RefCounted\n# Generated by tools/build_sprite_regions.gd.\nconst DATA := {\n"
	for race in result:
		text += "\t\"%s\": [\n" % race
		for frame in result[race]:
			text += "\t\t" + JSON.stringify(frame) + ",\n"
		text += "\t],\n"
	text += "}\n"
	var file := FileAccess.open("res://assets/characters/regions.gd", FileAccess.WRITE)
	file.store_string(text)
	quit()